service: pathofchild-es

plugins:
  - serverless-plugin-typescript

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):${self:custom.stage}}
  ideaTableStreamArn: ${cf:pathofchild-graphql-${self:custom.stage}.IdeaTableStreamArn}

package:
  exclude:
    - secrets.yml

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:${self:provider.region}:*:*

functions:
  idea:
    handler: lib/handler.idea
    events:
      - stream:
          type: dynamodb
          arn: ${self:custom.ideaTableStreamArn}
