service: pathofchild-graphql

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-offline-dynamodb-stream
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):${self:custom.stage}}
  serverless-offline:
    httpPort: 3010
  dynamodbStream:
    host: ${self:custom.secrets.LOCAL_DYNAMODB_HOST}
    port: ${self:custom.secrets.LOCAL_DYNAMODB_PORT}
    pollForever: true
    streams:
      - table: ${self:custom.secrets.LOCAL_DYNAMODB_TABLE}
        functions:
          - handle

package:
  exclude:
    - secrets.yml

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:${self:provider.region}:*:*
  environment:
    LOCAL_DYNAMODB_HOST: ${self:custom.secrets.LOCAL_DYNAMODB_HOST}
    LOCAL_DYNAMODB_PORT: ${self:custom.secrets.LOCAL_DYNAMODB_PORT}
    LOCAL_DYNAMODB_TABLE: ${self:custom.secrets.LOCAL_DYNAMODB_TABLE}
    ELASTIC_SEARCH_INDEX: ${self:custom.secrets.ELASTIC_SEARCH_INDEX}
    ELASTIC_SEARCH_HOST: ${self:custom.secrets.ELASTIC_SEARCH_HOST}
    AUTH0_CLIENT_ID: ${self:custom.secrets.AUTH0_CLIENT_ID}
    AUTH0_JWKS_URI: ${self:custom.secrets.AUTH0_JWKS_URI}
    AUTH0_JWKS_KID: ${self:custom.secrets.AUTH0_JWKS_KID}

functions:
  customAuthorizer:
    handler: lib/handler.auth
  graphql:
    handler: lib/handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer: customAuthorizer
  handle:
    handler: lib/handler.handle
    events:
      - stream:
          enabled: true
          type: dynamodb
