service: pathofchild-graphql

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  buildTable: ${self:service}-${self:custom.stage}-build
  childTable: ${self:service}-${self:custom.stage}-child
  gamificationTable: ${self:service}-${self:custom.stage}-gamification
  questTable: ${self:service}-${self:custom.stage}-quest
  userTable: ${self:service}-${self:custom.stage}-user
  whitelistItemTable: ${self:service}-${self:custom.stage}-whitelist-item
  secrets: ${file(secrets.yml):${self:custom.stage}}
  serverless-offline:
    port: 4001
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: ${self:custom.buildTable}
            sources: [./fixtures/build.json]
          - table: ${self:custom.childTable}
            sources: [./fixtures/child.json]
          - table: ${self:custom.gamificationTable}
            sources: [./fixtures/gamification.json]
          - table: ${self:custom.questTable}
            sources: [./fixtures/quest.json]
          - table: ${self:custom.userTable}
            sources: [./fixtures/user.json]
          - table: ${self:custom.whitelistItemTable}
            sources: [./fixtures/whitelist-item.json]

package:
  exclude:
    - secrets.yml

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:${self:provider.region}:*:*
  environment:
    AUTH0_CLIENT_ID: ${self:custom.secrets.AUTH0_CLIENT_ID}
    AUTH0_JWKS_URI: ${self:custom.secrets.AUTH0_JWKS_URI}
    AUTH0_JWKS_KID: ${self:custom.secrets.AUTH0_JWKS_KID}
    BUILD_TABLE: ${self:custom.buildTable}
    CHILD_TABLE: ${self:custom.childTable}
    GAMIFICATION_TABLE: ${self:custom.gamificationTable}
    QUEST_TABLE: ${self:custom.questTable}
    USER_TABLE: ${self:custom.userTable}
    WHITELIST_ITEM_TABLE: ${self:custom.whitelistItemTable}

functions:
  customAuthorizer:
    handler: lib/handler.auth
  graphql:
    handler: lib/handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer: customAuthorizer
  build:
    handler: lib/handler.build
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - BuildTable
              - StreamArn

resources:
  Resources:
    BuildTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.buildTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    ChildTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.childTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    GamificationTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.gamificationTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    QuestTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.questTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    UserTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.userTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    WhitelistItemTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.whitelistItemTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
  Outputs:
    BuildTableArn:
      Description: The ARN for the Build Table
      Value:
        "Fn::GetAtt": [ BuildTable, Arn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:BuildTableArn
    ChildTableArn:
      Description: The ARN for the Child Table
      Value:
        "Fn::GetAtt": [ ChildTable, Arn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:ChildTableArn
    GamificationTableArn:
      Description: The ARN for the Gamification Table
      Value:
        "Fn::GetAtt": [ GamificationTable, Arn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:GamificationTableArn
    QuestTableArn:
      Description: The ARN for the Quest Table
      Value:
        "Fn::GetAtt": [ QuestTable, Arn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:QuestTableArn
    UserTableArn:
      Description: The ARN for the User Table
      Value:
        "Fn::GetAtt": [ UserTable, Arn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:UserTableArn
    WhitelistItemTableArn:
      Description: The ARN for the WhitelistItem Table
      Value:
        "Fn::GetAtt": [ WhitelistItemTable, Arn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:WhitelistItemTableArn
