service: pathofchild-graphql

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local

custom:
  stage: ${opt:stage, self:provider.stage}
  ideaTable: ${self:service}-${self:custom.stage}-idea
  ideaUserTable: ${self:service}-${self:custom.stage}-idea-user
  userTable: ${self:service}-${self:custom.stage}-user
  secrets: ${file(secrets.yml):${self:custom.stage}}
  serverless-offline:
    port: 4001
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: ${self:custom.ideaTable}
            sources: [./fixtures/idea.json]
          - table: ${self:custom.ideaUserTable}
            sources: [./fixtures/idea-user.json]
          - table: ${self:custom.userTable}
            sources: [./fixtures/user.json]

package:
  exclude:
    - secrets.yml

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  stage: dev
  profile: thommas
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:${self:provider.region}:*:*
  environment:
    LOCAL_DYNAMODB_HOST: ${self:custom.secrets.LOCAL_DYNAMODB_HOST}
    LOCAL_DYNAMODB_PORT: ${self:custom.secrets.LOCAL_DYNAMODB_PORT}
    ELASTIC_SEARCH_INDEX: ${self:custom.secrets.ELASTIC_SEARCH_INDEX}
    ELASTIC_SEARCH_HOST: ${self:custom.secrets.ELASTIC_SEARCH_HOST}
    AUTH0_CLIENT_ID: ${self:custom.secrets.AUTH0_CLIENT_ID}
    AUTH0_JWKS_URI: ${self:custom.secrets.AUTH0_JWKS_URI}
    AUTH0_JWKS_KID: ${self:custom.secrets.AUTH0_JWKS_KID}
    IDEA_TABLE: ${self:custom.ideaTable}
    IDEA_USER_TABLE: ${self:custom.ideaUserTable}
    USER_TABLE: ${self:custom.userTable}

functions:
  customAuthorizer:
    handler: lib/handler.auth
  graphql:
    handler: lib/handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer: customAuthorizer
  idea:
    handler: lib/handler.idea
    events:
      - stream:
          enabled: true
          type: dynamodb
          tableName: pathofchild-graphql-dev-idea

resources:
  Resources:
    IdeaTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.secrets.READ_CAPACITY_UNITS}
          WriteCapacityUnits: ${self:custom.secrets.WRITE_CAPACITY_UNITS}
        TableName: ${self:custom.ideaTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    IdeaUserTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.secrets.READ_CAPACITY_UNITS}
          WriteCapacityUnits: ${self:custom.secrets.WRITE_CAPACITY_UNITS}
        TableName: ${self:custom.ideaUserTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    UserTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.secrets.READ_CAPACITY_UNITS}
          WriteCapacityUnits: ${self:custom.secrets.WRITE_CAPACITY_UNITS}
        TableName: ${self:custom.userTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
  Outputs:
    IdeaTableStreamArn:
      Description: The StreamArn for the Idea Table
      Value:
        "Fn::GetAtt": [ IdeaTable, StreamArn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:IdeaTableStreamArn
    IdeaUserTableStreamArn:
      Description: The StreamArn for the IdeaUser Table
      Value:
        "Fn::GetAtt": [ IdeaUserTable, StreamArn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:IdeaUserTableStreamArn
    UserTableStreamArn:
      Description: The StreamArn for the User Table
      Value:
        "Fn::GetAtt": [ UserTable, StreamArn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:UserTableStreamArn
