service: pathofchild-graphql

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  childTable: ${self:service}-${self:custom.stage}-child
  taskTable: ${self:service}-${self:custom.stage}-task
  userTable: ${self:service}-${self:custom.stage}-user
  secrets: ${file(secrets.yml):${self:custom.stage}}
  serverless-offline:
    port: 4001
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: ${self:custom.childTable}
            sources: [./fixtures/child.json]
          - table: ${self:custom.taskTable}
            sources: [./fixtures/task.json]
          - table: ${self:custom.userTable}
            sources: [./fixtures/user.json]

package:
  exclude:
    - secrets.yml

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:${self:provider.region}:*:*
  environment:
    LOCAL_DYNAMODB_ENDPOINT: ${self:custom.secrets.LOCAL_DYNAMODB_ENDPOINT}
    AUTH0_CLIENT_ID: ${self:custom.secrets.AUTH0_CLIENT_ID}
    AUTH0_JWKS_URI: ${self:custom.secrets.AUTH0_JWKS_URI}
    AUTH0_JWKS_KID: ${self:custom.secrets.AUTH0_JWKS_KID}
    CHILD_TABLE: ${self:custom.childTable}
    TASK_TABLE: ${self:custom.taskTable}
    USER_TABLE: ${self:custom.userTable}

functions:
  customAuthorizer:
    handler: lib/handler.auth
  graphql:
    handler: lib/handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer: customAuthorizer

resources:
  Resources:
    ChildTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.secrets.READ_CAPACITY_UNITS}
          WriteCapacityUnits: ${self:custom.secrets.WRITE_CAPACITY_UNITS}
        TableName: ${self:custom.childTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    TaskTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.secrets.READ_CAPACITY_UNITS}
          WriteCapacityUnits: ${self:custom.secrets.WRITE_CAPACITY_UNITS}
        TableName: ${self:custom.taskTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    UserTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.secrets.READ_CAPACITY_UNITS}
          WriteCapacityUnits: ${self:custom.secrets.WRITE_CAPACITY_UNITS}
        TableName: ${self:custom.userTable}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
  Outputs:
    ChildTableStreamArn:
      Description: The StreamArn for the Child Table
      Value:
        "Fn::GetAtt": [ ChildTable, StreamArn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:ChildTableStreamArn
    TaskTableStreamArn:
      Description: The StreamArn for the Task Table
      Value:
        "Fn::GetAtt": [ TaskTable, StreamArn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:TaskTableStreamArn
    UserTableStreamArn:
      Description: The StreamArn for the User Table
      Value:
        "Fn::GetAtt": [ UserTable, StreamArn ]
      Export:
        Name: ${self:service}:${self:custom.stage}:UserTableStreamArn
