service: graphql-api

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):${self:custom.stage}}
  serverless-offline:
    port: 4001
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: build
            sources: [./fixtures/build.json]
          - table: child
            sources: [./fixtures/child.json]
          - table: quest
            sources: [./fixtures/quest.json]
          - table: user
            sources: [./fixtures/user.json]
          - table: whitelist_item
            sources: [./fixtures/whitelist-item.json]

package:
  exclude:
    - secrets.yml

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:eu-west-1:*:*
  environment:
    API_KEY: "${self:custom.secrets.API_KEY}"
    API_SECRET: "${self:custom.secrets.API_SECRET}"
    COMMON_API_KEY: "${self:custom.secrets.COMMON_API_KEY}"
    COMMON_API_SECRET: "${self:custom.secrets.COMMON_API_SECRET}"

functions:
  graphql:
    handler: lib/handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer: customAuthorizer
  customAuthorizer:
    handler: lib/handler.auth

resources:
  Resources:
    buildTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'build'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    childTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'child'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    questTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'quest'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    userTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'user'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    whitelistItemTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'whitelist_item'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
